feat: export body of node definition into function
flowr-analysis/flowr-df-visualizer pull request #10
Opened 2024-03-25 10:30 UTC by Core5563

2024-04-10 07:29 UTC, EagleoutIce commented
* [ ] Unify new style with `React.FC` to signal functional components
* [ ] Add edge types (with arrow-heads)

2024-04-11 09:31 UTC, EagleoutIce requested changes

2024-04-11 09:31 UTC, EagleoutIce commented on source/components/model/edges/edgeDefinition.tsx
> +}
Please use a record like this (you should be able to just apply the suggestion). You can use a map as well if you want:

```suggestion
const edgeTagMap = {
  'reads':               'readsEdge',
  'defined-by':          'definedByEdge',
  'same-read-read':      'sameReadReadEdge',
  'same-def-def':        'sameDefDefEdge',
  'calls':               'callsEdge',
  'returns':             'returnsEdge',
  'defines-on-call':     'definesOnCallEdge',
  'defined-by-on-call':  'definedByOnCallEdge',
  'argument':            'argumentEdge',
  'side-effect-on-call': 'sideEffectOnCallEdge',
  'relates':             'relatesEdge'
};

function edgeTagMapper(edgeTag: string): string {
  return edgeTagMap[edgeTag] ?? '';
}
```

2024-04-11 09:31 UTC, EagleoutIce commented on source/components/model/edges/edgeDefinition.tsx
> +    <EdgeLabelRenderer>
We could abstract this as a component as well, but that might be fine later (so we should make an issue for this).

2024-04-11 09:31 UTC, EagleoutIce commented on source/components/model/edges/edgeDefinition.tsx
> +    id = {id}
there is a lot of repetition here which we may want to "abstract away"

2024-04-11 09:31 UTC, EagleoutIce commented on source/components/model/nodes/nodeDefinition.tsx
> +        <span className='hover-over-text'>
fine for now, and a nice intermediate solution :) 

We could make a "hover-over-component" for this if you want. What is your opinion?

2024-04-14 08:24 UTC, Core5563 commented on source/components/model/nodes/nodeDefinition.tsx
> +        <span className='hover-over-text'>
seems like a good idea

2024-05-12 14:07 UTC, Core5563 commented on source/components/model/edges/edgeDefinition.tsx
> +    <EdgeLabelRenderer>
Ive created an Issue for this: #13

2024-05-12 14:07 UTC, Core5563 commented on source/components/model/edges/edgeDefinition.tsx
> +    id = {id}
I've created an issue for this: #13

2024-08-11 09:57 UTC, merged